app:
    image: node:12
    container_name: app
    command: bash -c "npm i && npm run build && npm run start:dev"
    restart: always
    working_dir: /var/www/app
    volumes:
        - ./:/var/www/app:cached
    ports:
        - 3000:3000